### ISSUE TITLE
Error during installation (requirements)

### ISSUE THREAD

**Issue by bjohas** [edtechhub/gtasks#8]
```
sudo pip install -r requirements.txt
```
gives
```
...
ImportError: No module named requests_oauthlib
```

**Comment by Resinderate** [comment]
Ah I see, it looks like the installer itself depends on some external libraries, so they need to be installed before the main app. I've updated the README on `develop` and added a `pre-requirements.txt` so now we should do:
```
pip install -r pre-requirements.txt
pip install -r requirements.txt
```
As a two stage install.

**Comment by bjohas** [comment]
I'm now getting
```
Collecting keyring==19.2.0 (from -r pre-requirements.txt (line 2))
...
No matching distribution found for keyring==19.2.0 (from -r pre-requirements.txt (line 2))
```
Python 2.7.16, Ubuntu 19.04.

**Comment by Resinderate** [comment]
I think the `keyring` package will only work with Python 3.5+, and on linux it may also need manual installation of `dbus`[0] if pip doesn't handle it properly. I should be able to test this out with docker, as I've only tested with macOS.

[0] https://gitlab.freedesktop.org/dbus/dbus-python

**Comment by bjohas** [comment]
OK, great! With pip3 it works - after installing "testresources", which is still missing from pre-requirements?

**Comment by bjohas** [comment]
@Resinderate  - would you be able to add the right version of 'testresources' to the pre-requirements?

**Comment by Resinderate** [comment]
I tried to reproduce the issue with the `ubuntu:19.04` image but it seemed to go okay without `testresources`. I've added the latest version to the `pre-requirements.txt` so it should be fine now, I'll add some extra documentation to help for when you're installing on a system with both Python 2 / 3. I've also made the `gtasks` script itself look for `python3` instead of `python` to try and get ahead of issues like this in future 👍
